// Generated by https://quicktype.io

import 'dart:math';

class NasaModel {
  String? copyright;
  String? date;
  String? explanation;
  String? hdurl;
  String? mediaType;
  String? serviceVersion;
  String? title;
  String? url;

  NasaModel({
    this.copyright,
    this.date,
    this.explanation,
    this.hdurl,
    this.mediaType,
    this.serviceVersion,
    this.title,
    this.url,
  });
  factory NasaModel.fromMap(Map<String, dynamic> map) {
    return NasaModel(
        copyright: map['copyright'],
        date: map['date'],
        explanation: map['explanation'],
        hdurl: map['hdurl'],
        mediaType: map['mediaType'],
        serviceVersion: map['serviceVersion'],
        title: map['title'],
        url: map['url']);
  }

  Map<String, dynamic> toMap() {
    return {
      'copyright': copyright,
      'date': date,
      'explanation': explanation,
      'hdurl': hdurl,
      'mediaType': mediaType,
      'serviceVersion': serviceVersion,
      'title': title,
      'url': url
    };
  }
}
